name: Update Installer Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Detect modified files
        id: detect-changes
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Modified files: $FILES"
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Update minor version and commit message for modified files
        run: |
          for FILE in $FILES; do
            if [[ $FILE == *"install.sh"* ]]; then
              major=$(grep -oP 'INSTALLER_MAJOR="\K\d+' $FILE)
              minor=$(grep -oP 'INSTALLER_MINOR="\K\d+' $FILE)
              minor=$((minor + 1))
              sed -ri "s/(INSTALLER_MINOR=\")([0-9]+)/\1$minor/" $FILE
              git config --local user.email "vincenth@synaptics.com"
              git config --local user.name "Vincent Huang"
              git add $FILE
              git commit -m "Update installer version in $FILE to $major.$minor"
            fi
          done

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.INSTALL2_TOKEN }}